services:
  obsidian:
    build: .
    image: 'obsidian-remote:local'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8888:8080
      - 8443:8443
    volumes:
      - "${VAULTS_PATH}:/vaults"
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-git
